# 1. Konfigurasi Koneksi Database
spring.datasource.url=jdbc:mysql://localhost:3306/db_perpustakaan?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=

# 2. Driver MySQL
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# 3. Konfigurasi Hibernate / JPA
# update: Spring akan otomatis membuat/mengupdate tabel berdasarkan Entity Java Anda
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# Cek OpenAI in Security Config
# Mengurutkan tag berdasarkan abjad (A-Z)
springdoc.swagger-ui.tags-sorter=alpha
# Mengurutkan endpoint di dalam tag berdasarkan jalur (path) atau abjad
springdoc.swagger-ui.operations-sorter=alpha

# untuk memberitahu saya ketika ditolak
# logging.level.org.springframework.security=DEBUG